name = "awt"
description = "Ada Window Toolkit"
version = "0.1.0"
website = "https://github.com/onox/awt"
licenses = "Apache-2.0"
tags = ["egl", "wayland", "windows", "graphics", "opengl"]

authors = ["onox"]
maintainers = ["onox <denkpadje@gmail.com>"]
maintainers-logins = ["onox"]

[available.'case(os)']
linux = true
'...' = false

[project-files.'case(os)']
linux = ["awt-linux.gpr", "example/example.gpr"]

[[depends-on]]
[depends-on.'case(os)'.linux]
wayland_egl_ada = "^1.0"
wayland_cursor_ada = "^1.0"
wayland_protocols_ada = "^1.0"
orka_egl = "^1.0.0"

[[depends-on]]
orka = "~0.2.0"
