name = "orka_plugin_gltf"
description = "Orka plug-in for loading glTF models"
version = "1.0.0"
website = "https://github.com/onox/orka"
licenses = "Apache-2.0"
tags = ["gltf", "orka"]

authors = ["onox"]
maintainers = ["onox <denkpadje@gmail.com>"]
maintainers-logins = ["onox"]

[build-switches]
validation.compile_checks = "warnings"
"*".style_checks = ["-gnatygAOM99-Is"]

[[depends-on]]
json = "^5.0.3"
orka_transforms = "^1.0.0"
orka = "~1.0.0"

[[pins]]
orka = { path = "../orka" }
orka_transforms = { path = "../orka_transforms" }
